<?php
define("OAUTH_CONSUMER_KEY", getenv('TWITTER_CONSUMER_KEY'));
define("OAUTH_CONSUMER_SECRET", getenv('TWITTER_CONSUMER_SECRET'));
define("OAUTH_ACCESS_TOKEN", getenv('TWITTER_ACCESS_TOKEN'));
define("OAUTH_ACCESS_TOKEN_SECRET", getenv('TWITTER_ACCESS_TOKEN_SECRET'));
?>